[build]
  command = "npm run build"
  publish = "www/"

[functions]
  directory = "serverless/"

[[redirects]]
  from = "/txt"
  to = "/.netlify/functions/txt"
  status = 200

[[redirects]]
  from = "/json"
  to = "/.netlify/functions/json"
  status = 200
